#!/bin/bash
# (@)/my_backup
# A very simple backup scripts

# Change the TAPE device to match your system.
# Check /var/log/messages to determine tape device
# You may also need to add scsi-tape support to your kernel

TAPE=/dev/rft0

# Rewind the tape device $TAPE
mt $TAPE rew
# Get a list of home directories
HOMES= `grep /home /etc/passwd | cut -f6 -d':'`
# Back up the data in those directories
tar cvf $TAPE $HOMES
# Rewind and eject the tape.
mt $TAPE rewoffl
